{
 "title": "Brew!",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "PID Current Temperature",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "degree" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "pid_measured_temp", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "PID Requested Temperature",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "degree" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "pid_set_temp", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "PID Applied Power",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "pid_current_power_pct", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "PID Maximum Power",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "pid_max_power_pct", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Power",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 7, "x": 16, "y": 0 },
   "targets": [
    { "expr": "pid_max_power_pct", "legendFormat": "Maximum" },
    { "expr": "pid_current_power_pct", "legendFormat": "Current" }
   ]
  },
  {
   "title": "Serial Probe 1",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "degree" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "serialprobe_temp_1", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Serial Probe 2",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "degree" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "serialprobe_temp_2", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Serial Probe 3",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "degree" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "serialprobe_temp_3", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Serial Probe 4",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "degree" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "serialprobe_temp_4", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Temperature",
   "type": "timeseries",
   "gridPos": { "h": 17, "w": 23, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "degree" } },
   "targets": [
    { "expr": "pid_measured_temp", "legendFormat": "PID" },
    { "expr": "serialprobe_temp_1", "legendFormat": "Probe 1" },
    { "expr": "serialprobe_temp_2", "legendFormat": "Probe 2" },
    { "expr": "serialprobe_temp_3", "legendFormat": "Probe 3" },
    { "expr": "serialprobe_temp_4", "legendFormat": "Probe 4" }
   ]
  }
 ]
}